server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: gateway-service
  main:
    banner-mode: off
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: otpModule
          #uri: http://localhost:8081/
          uri: http://otp-ds-myproject.192.168.99.103.nip.io/
          predicates:
            - Path=/otp/**
        - id: communicationModule
          uri: http://communication-ds-myproject.192.168.99.103.nip.io/
          #uri: http://localhost:8082/
          predicates:
            - Path=/communication/**
      rate-limit:
        enabled: true
        repository: JPA
        policy-list:
          otpModule:
            - limit: 5
              refresh-interval: 60
              type:
                - origin
          communicationModule:
            - limit: 1
              refresh-interval: 2
              type:
                - origin


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-ds-myproject.192.168.99.103.nip.io/auth/realms/uj
          #issuer-uri: http://localhost:8083/auth/realms/uj
          #jwk-set-uri: http://localhost:8083/auth/realms/uj/protocol/openid-connect/certs
          jwk-set-uri: http://auth-ds-myproject.192.168.99.103.nip.io/auth/realms/uj/protocol/openid-connect/certs
