server:
  port: 9999

spring:
  profiles:
    active: local
  application:
    name: gateway-service
  main:
    banner-mode: off
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: otpModule
          uri: http://localhost:8081/
          predicates:
            - Path=/otp/**
        - id: communicationModule
          uri: http://localhost:8082/
          predicates:
            - Path=/communication/**
      rate-limit:
        enabled: true
        repository: JPA
        policy-list:
          otpModule:
            - limit: 5
              refresh-interval: 60
              type:
                - origin
          communicationModule:
            - limit: 1
              refresh-interval: 2
              type:
                - origin


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

  boot:
    admin:
      client:
        url: http://localhost:7777/admin
        username: admin
        password: admin123

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
